# R Data Structures

## Data Structures

Data structures are used to store and organize values.

R provides many built-in data structures. Each is used to handle data in different ways:

- Vectors

- Lists

- Matrices

- Arrays

- Data Frames

## R Vectors

### Vectors

A vector is simply a list of items that are of the same type.

To combine the list of items to a vector, use the c() function and separate the items by a comma.

In the example below, we create a vector variable called fruits, that combine strings:

In [144]:
# Example
# Vector of strings
fruits <- c("banana", "apple", "orange") # NOTE: In R, c() means "combine" or "concantenate"
                                         # It is used to put multiple similar values together into a single vector.
                                         # All the values inside c() must be same type (or R will convert them)

# Print fruits
fruits

[1] "banana" "apple"  "orange"

In [145]:
b <- c(1, "A", TRUE)

b
# NOTE: Everything becomes character

[1] "1"    "A"    "TRUE"

In this example, we create a vector that combines numerical values:

In [146]:
# Example
# Vector of numerical values
numbers <- c(1, 2, 3)

# Print numbers
numbers

[1] 1 2 3

To create a vector with numerical values in a sequence, use the : operator:

In [147]:
# Example
# Vector with numerical values in a sequence
numbers <- 1:10

numbers

 [1]  1  2  3  4  5  6  7  8  9 10

You can also create numerical values with decimals in a sequence, but note that if the last element does not belong to the sequence, it is not used:

In [148]:
# Example
# Vector with numerical decimals in a sequence
numbers1 <- 1.5:6.5
numbers1

# Vector with numerical decimals in a sequence where the last element is not used
numbers2 <- 1.5:6.3
numbers2

[1] 1.5 2.5 3.5 4.5 5.5 6.5

[1] 1.5 2.5 3.5 4.5 5.5

In the example below, we create a vector of logical values:

In [149]:
# Example
# Vector of logical values
log_values <- c(TRUE, FALSE, TRUE, FALSE)

log_values

[1]  TRUE FALSE  TRUE FALSE

Vector Length
To find out how many items a vector has, use the length() function:

In [150]:
# Example
fruits <- c("banana", "apple", "orange")

length(fruits)

[1] 3

Sort a Vector
To sort items in a vector alphabetically or numerically, use the sort() function:

In [151]:
# Example
fruits <- c("banana", "apple", "orange", "mango", "lemon")
numbers <- c(13, 3, 5, 7, 20, 2)

sort(fruits)  # Sort a string
sort(numbers) # Sort numbers

[1] "apple"  "banana" "lemon"  "mango"  "orange"

[1]  2  3  5  7 13 20

## Access Vectors

You can access the vector items by referring to its index number inside brackets []. The first item has index 1, the second item has index 2, and so on:

In [152]:
# Example
fruits <- c("banana", "apple", "orange")

# Access the first item (banana)
fruits[1]

[1] "banana"

You can also access multiple elements by referring to different index positions with the c() function:

In [153]:
# Example
fruits <- c("banana", "apple", "orange", "mango", "lemon")

# Access the first and third item (banana and orange)
fruits[c(1, 3)]

[1] "banana" "orange"

You can also use negative index numbers to access all items except the ones specified:

In [154]:
# Example
fruits <- c("banana", "apple", "orange", "mango", "lemon")

# Access all items except for the first item
fruits[c(-1)]
fruits[-1]

[1] "apple"  "orange" "mango"  "lemon"

[1] "apple"  "orange" "mango"  "lemon"

Change an Item

To change the value of a specific item, refer to the index number:

In [155]:
# Example
fruits <- c("banana", "apple", "orange", "mango", "lemon")

# Change "banana" to "pear"
fruits[1] <- "pear"

# Print fruits
fruits

[1] "pear"   "apple"  "orange" "mango"  "lemon"

Replace Multiple Items at Once (By Index)

In [156]:
# Example
fruits <- c("banana", "apple", "orange", "mango", "lemon")

# Change "banana" to "pear"
fruits[c(2, 4)] <- c("pear", "grape")

# Print fruits
fruits

[1] "banana" "pear"   "orange" "grape"  "lemon"

Repeat Vectors

To repeat vectors, use the rep() function:

rep() means repeat values in a vector.

In [157]:
# Example
# Repeat each value:

repeat_each <- rep(c(1,2,3), each = 3) # Note: Repeat each individual element three times before moving to the next.

repeat_each

[1] 1 1 1 2 2 2 3 3 3

In [158]:
# Example
# Repeat the sequence of the vector:

repeat_times <- rep(c(1,2,3), times = 3)

repeat_times

[1] 1 2 3 1 2 3 1 2 3

In [159]:
# Example
# Repeat each value independently:

repeat_indepent <- rep(c(1,2,3), times = c(5,2,1)) # This type of repetition is called Element-wise repetition
                                                   # This is because each value is repeated independently based on its corresponding count.
                                                   # Each number repeats based on it's own instruction.

repeat_indepent

[1] 1 1 1 1 1 2 2 3

Generating Sequenced Vectors

One of the examples on top, showed you how to create a vector with numerical values in a sequence with the : operator:

In [160]:
# Example
numbers <- 1:10

numbers

 [1]  1  2  3  4  5  6  7  8  9 10

To make bigger or smaller steps in a sequence, use the seq() function:

In [161]:
# Example
numbers <- seq(from = 0, to = 100, by = 20) # Note: by controls the step size

numbers

[1]   0  20  40  60  80 100

**Note: The seq() function has three parameters: from is where the sequence starts, to is where the sequence stops, and by is the interval of the sequence.**

## R Lists

### Lists

A list in R can contain many different data types inside it. A list is a collection of data which is ordered and changeable.

To create a list, use the list() function:

In [162]:
# Example
# List of strings
thislist <- list("apple", "banana", "cherry")

# Print the list
thislist

[[1]]
[1] "apple"

[[2]]
[1] "banana"

[[3]]
[1] "cherry"

### Access Lists

You can access the list items by referring to its index number, inside brackets. The first item has index 1, the second item has index 2, and so on:

In [163]:
# Example
thislist <- list("apple", "banana", "cherry")

thislist[1]

[[1]]
[1] "apple"

### Change Item Value

To change the value of a specific item, refer to the index number:

In [164]:
# Example
thislist <- list("apple", "banana", "cherry")
thislist[1] <- "blackcurrant"

# Print the updated list
thislist

[[1]]
[1] "blackcurrant"

[[2]]
[1] "banana"

[[3]]
[1] "cherry"

### List Length

To find out how many items a list has, use the length() function:

In [165]:
# Example

thislist <- list("apple", "banana", "cherry")

length(thislist)

[1] 3

### Check if Item Exists

To find out if a specified item is present in a list, use the %in% operator:

In [166]:
# Example
# Check if "apple" is present in the list:

thislist <- list("apple", "banana", "cherry")

"apple" %in% thislist

[1] TRUE

### Add List Items

To add an item to the end of the list, use the append() function:

In [167]:
# Example
# Add "orange" to the list:

thislist <- list("apple", "banana", "cherry")

append(thislist, "orange")

[[1]]
[1] "apple"

[[2]]
[1] "banana"

[[3]]
[1] "cherry"

[[4]]
[1] "orange"

To add an item to the right of a specified index, add "after=index number" in the append() function:

In [168]:
# Example
# Add "orange" to the list after "banana" (index 2):

thislist <- list("apple", "banana", "cherry")

append(thislist, "orange", after = 2)

[[1]]
[1] "apple"

[[2]]
[1] "banana"

[[3]]
[1] "orange"

[[4]]
[1] "cherry"

### Remove List Items

You can also remove list items. The following example creates a new, updated list without an "apple" item:

In [169]:
# Example
# Remove "apple" from the list:

thislist <- list("apple", "banana", "cherry")

newlist <- thislist[-1]

# Print the new list
newlist

[[1]]
[1] "banana"

[[2]]
[1] "cherry"

### Range of Indexes

You can specify a range of indexes by specifying where to start and where to end the range, by using the : operator:

In [170]:
# Example
# Return the second, third, fourth and fifth item:

thislist <- list("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")

(thislist)[2:5]

[[1]]
[1] "banana"

[[2]]
[1] "cherry"

[[3]]
[1] "orange"

[[4]]
[1] "kiwi"

### Loop Through a List

You can loop through the list items by using a for loop:

In [171]:
# Example
# Print all items in the list, one by one:

thislist <- list("apple", "banana", "cherry")

for (x in thislist) {
  print(x)
}

[1] "apple"
[1] "banana"
[1] "cherry"

### Join Two Lists

There are several ways to join, or concatenate, two or more lists in R.

The most common way is to use the c() function, which combines two elements together:

In [172]:
# Example
list1 <- list("a", "b", "c")
list2 <- list(1,2,3)
list3 <- c(list1,list2)

list3

[[1]]
[1] "a"

[[2]]
[1] "b"

[[3]]
[1] "c"

[[4]]
[1] 1

[[5]]
[1] 2

[[6]]
[1] 3

# R Matrices

## Matrices

A matrix is a two dimensional data set with columns and rows.

A column is a vertical representation of data, while a row is a horizontal representation of data.

A matrix can be created with the matrix() function. Specify the nrow and ncol parameters to get the amount of rows and columns:

In [173]:
# Example
# Create a matrix
thismatrix <- matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 2) # Note: Remember the c() function is used to concatenate items together.

# Print the matrix
thismatrix

     [,1] [,2]
[1,] 1    4
[2,] 2    5
[3,] 3    6

#### You can also create a matrix with strings:

In [174]:
# Example
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix

     [,1]   [,2]
[1,] apple  cherry
[2,] banana orange

## Access Matrix Items

You can access the items by using [ ] brackets. The first number "1" in the bracket specifies the row-position, while the second number "2" specifies the column-position:

In [175]:
# Example
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix[1, 2]

[1] "cherry"

#### The whole row can be accessed if you specify a comma after the number in the bracket:

In [176]:
# Example
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix[2,]

[1] "banana" "orange"

The whole column can be accessed if you specify a comma before the number in the bracket:

In [177]:
# Example
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix[,2]

[1] "cherry" "orange"

## Access More Than One Row

More than one row can be accessed if you use the c() function:

In [178]:
# Example
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

thismatrix[c(1,2),]

     [,1]   [,2]   [,3]
[1,] apple  orange pear
[2,] banana grape  melon

## Access More Than One Column

More than one column can be accessed if you use the c() function:

In [179]:
# Example
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

thismatrix[, c(1,2)]

     [,1]   [,2]
[1,] apple  orange
[2,] banana grape
[3,] cherry pineapple

## Add Rows and Columns

Use the cbind() function to add additional columns in a Matrix:

In [180]:
# Example

thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

newmatrix <- cbind(thismatrix, c("strawberry", "blueberry", "raspberry"))

# Print the new matrix
newmatrix

     [,1]   [,2]      [,3]  [,4]
[1,] apple  orange    pear  strawberry
[2,] banana grape     melon blueberry
[3,] cherry pineapple fig   raspberry

`Note: The cells in the new column must be of the same length as the existing matrix.`

#### Use the rbind() function to add additional rows in a Matrix:

In [181]:
# Example

thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

newmatrix <- rbind(thismatrix, c("strawberry", "blueberry", "raspberry"))

# Print the new matrix
newmatrix

     [,1]       [,2]      [,3]
[1,] apple      orange    pear
[2,] banana     grape     melon
[3,] cherry     pineapple fig
[4,] strawberry blueberry raspberry

`Note: The cells in the new row must be of the same length as the existing matrix.`

#### Remove Rows and Columns

Use the c() function to remove rows and columns in a Matrix:

In [182]:
# Example

thismatrix <- matrix(c("apple", "banana", "cherry", "orange", "mango", "pineapple"), nrow = 3, ncol =2)

#Remove the first row and the first column
thismatrix <- thismatrix[-c(1), -c(1)]

thismatrix

[1] "mango"     "pineapple"

## Check if an Item Exists

To find out if a specified item is present in a matrix, use the %in% operator:

In [183]:
# Example
# Check if "apple" is present in the matrix:

thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

"apple" %in% thismatrix

[1] TRUE

## Number of Rows and Columns

Use the dim() function to find the number of rows and columns in a Matrix:

In [184]:
# Example
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

dim(thismatrix)

[1] 2 2

## Matrix Length

Use the length() function to find the dimension of a Matrix:

In [185]:
# Example
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

length(thismatrix)

[1] 4

`Total cells in the matrix is the number of rows multiplied by number of columns.`

`In the example above: Dimension = 2*2 = 4.`

## Loop Through a Matrix

You can loop through a Matrix using a for loop. The loop will start at the first row, moving right:

In [186]:
# Example
# Loop through the matrix items and print them:

thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

for (rows in 1:nrow(thismatrix)) {
  for (columns in 1:ncol(thismatrix)) {
    print(thismatrix[rows, columns])
  }
}

[1] "apple"
[1] "cherry"
[1] "banana"
[1] "orange"

## Combine two Matrices

Again, you can use the rbind() or cbind() function to combine two or more matrices together:

In [187]:
# Example
# Combine matrices
Matrix1 <- matrix(c("apple", "banana", "cherry", "grape"), nrow = 2, ncol = 2)
Matrix2 <- matrix(c("orange", "mango", "pineapple", "watermelon"), nrow = 2, ncol = 2)

# Adding it as a rows
Matrix_Combined <- rbind(Matrix1, Matrix2)
Matrix_Combined

# Adding it as a columns
Matrix_Combined <- cbind(Matrix1, Matrix2)
Matrix_Combined

     [,1]   [,2]
[1,] apple  cherry
[2,] banana grape
[3,] orange pineapple
[4,] mango  watermelon

     [,1]   [,2]   [,3]   [,4]
[1,] apple  cherry orange pineapple
[2,] banana grape  mango  watermelon

# R Arrays

## Arrays

Compared to matrices, arrays can have more than two dimensions.

We can use the array() function to create an array, and the dim parameter to specify the dimensions:

In [188]:
# Example
# An array with one dimension with values ranging from 1 to 24
thisarray <- c(1:24)
thisarray

# An array with more than one dimension
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

Example Explained

In the example above we create an array with the values 1 to 24.

How does dim=c(4,3,2) work?

The first and second number in the bracket specifies the amount of rows and columns.

The last number in the bracket specifies how many dimensions we want.

Note: Arrays can only have one data type.

# Access Array Items

You can access the array elements by referring to the index position. You can use the [] brackets to access the desired elements from an array:

In [189]:
# Example
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

multiarray[2, 3, 2]

[1] 22

`The syntax is as follow: array[row position, column position, matrix level]`

#### You can also access the whole row or column from a matrix in an array, by using the c() function:

In [190]:
# Example
thisarray <- c(1:24)

# Access all the items from the first row from matrix one
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray[c(1),,1]

# Access all the items from the first column from matrix one
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray[,c(1),1]

[1] 1 5 9

[1] 1 2 3 4

A comma (,) before c() means that we want to access the column.

A comma (,) after c() means that we want to access the row.

## Check if an Item Exists

To find out if a specified item is present in an array, use the %in% operator:

In [191]:
# Example
# Check if the value "2" is present in the array:

thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

2 %in% multiarray

[1] TRUE

## Amount of Rows and Columns

Use the dim() function to find the amount of rows and columns in an array:

In [192]:
# Example
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

dim(multiarray)

[1] 4 3 2

## Array Length

Use the length() function to find the dimension of an array:

In [193]:
# Example
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

length(multiarray)

[1] 24

## Loop Through an Array

You can loop through the array items by using a for loop:

In [194]:
# Example
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

for(x in multiarray){
  print(x)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20
[1] 21
[1] 22
[1] 23
[1] 24