# Data Cleaning and Data Manipulation with R Programming

## Practical Industry Masterclass

**Kajola Gbenga**  
**Data Scientist & AI Engineer**

This notebook is a comprehensive, hands-on course for cleaning, transforming, validating, and preparing messy data for analysis and machine learning using R and RStudio.

### Primary practical dataset

The main case study is the uploaded Excel workbook:

`robust_dirty_powerbi_dataset.xlsx`

The workbook is inspected first so that the exercises are grounded in the actual structure and dirty-data patterns present in the supplied dataset.

### Course objectives

By the end of this masterclass, learners should be able to:

- audit a raw dataset systematically
- identify and standardize dirty column names
- inspect and convert data types safely
- detect and handle missing values
- identify exact and business-level duplicates
- clean text, categories, IDs, emails, and phone numbers
- parse currencies, percentages, dates, and numbers
- detect and investigate suspicious numeric values and outliers
- reshape wide and long data
- filter, sort, mutate, group, summarize, and aggregate data
- join datasets while protecting data integrity
- validate data against business rules
- automate repetitive cleaning tasks
- process multiple files
- build reusable cleaning functions
- handle errors robustly
- introduce `data.table`, Arrow, and Parquet for larger datasets

> Teaching principle: cleaning is not simply deleting bad-looking values. Every transformation should have a reason, a documented rule, and a validation step.

## Workbook profile

The following information was generated from the uploaded workbook before the R exercises were written.

### Sheet: `Sales_Data`

- Rows: **100**
- Columns: **7**

**Columns**

`OrderID, Date, Customer Name, Region, Sales Amount, Product, Quantity`

**Observed R/Python-readable source types**

```text
{
  "OrderID": "int64",
  "Date": "object",
  "Customer Name": "object",
  "Region": "object",
  "Sales Amount": "object",
  "Product": "object",
  "Quantity": "float64"
}
```

**First five records**

```text
[
  {
    "OrderID": "1001",
    "Date": "",
    "Customer Name": "John Doe",
    "Region": "PH",
    "Sales Amount": "",
    "Product": "Laptop",
    "Quantity": "3.0"
  },
  {
    "OrderID": "1002",
    "Date": "March 3 2024",
    "Customer Name": "Rachel Zane",
    "Region": "Abuja ",
    "Sales Amount": "50000",
    "Product": "Monitor",
    "Quantity": "1.0"
  },
  {
    "OrderID": "1003",
    "Date": "2024/01/05",
    "Customer Name": "Harvey Specter",
    "Region": "",
    "Sales Amount": "45000",
    "Product": "Tablet",
    "Quantity": "1.0"
  },
  {
    "OrderID": "1004",
    "Date": "",
    "Customer Name": "Rachel Zane",
    "Region": "",
    "Sales Amount": "50000",
    "Product": "Phone",
    "Quantity": ""
  },
  {
    "OrderID": "1005",
    "Date": "",
    "Customer Name": "Louis Litt",
    "Region": "PH",
    "Sales Amount": "60000",
    "Product": "Monitor",
    "Quantity": "1.0"
  }
]
```

### Sheet: `Customers`

- Rows: **100**
- Columns: **5**

**Columns**

`CustomerID, Name, Email, Phone, Age`

**Observed R/Python-readable source types**

```text
{
  "CustomerID": "int64",
  "Name": "object",
  "Email": "object",
  "Phone": "float64",
  "Age": "object"
}
```

**First five records**

```text
[
  {
    "CustomerID": "1",
    "Name": "",
    "Email": "john@email.com",
    "Phone": "",
    "Age": "25"
  },
  {
    "CustomerID": "2",
    "Name": "Donna Paulsen",
    "Email": "john@email.com",
    "Phone": "",
    "Age": "30"
  },
  {
    "CustomerID": "3",
    "Name": "Louis Litt",
    "Email": "user@mail.com",
    "Phone": "8012345678.0",
    "Age": "Twenty Five"
  },
  {
    "CustomerID": "4",
    "Name": "Harvey Specter",
    "Email": "",
    "Phone": "8012345678.0",
    "Age": "35"
  },
  {
    "CustomerID": "5",
    "Name": "Louis Litt",
    "Email": "user@mail.com",
    "Phone": "",
    "Age": "30"
  }
]
```

### Sheet: `Products`

- Rows: **50**
- Columns: **4**

**Columns**

`ProductID, Product Name, Category, Price`

**Observed R/Python-readable source types**

```text
{
  "ProductID": "int64",
  "Product Name": "object",
  "Category": "object",
  "Price": "object"
}
```

**First five records**

```text
[
  {
    "ProductID": "1",
    "Product Name": "Tablet",
    "Category": "electronics",
    "Price": "500,000"
  },
  {
    "ProductID": "2",
    "Product Name": "Tablet",
    "Category": "electronics",
    "Price": "200000"
  },
  {
    "ProductID": "3",
    "Product Name": "Tablet",
    "Category": "electronics",
    "Price": "150000NGN"
  },
  {
    "ProductID": "4",
    "Product Name": "Monitor",
    "Category": "Electronics ",
    "Price": "200000"
  },
  {
    "ProductID": "5",
    "Product Name": "Phone",
    "Category": "",
    "Price": "500,000"
  }
]
```

# PART 1 - Foundations of Data Cleaning

## 1. What is data cleaning?

Data cleaning is the process of identifying, correcting, standardizing, documenting, and validating data-quality problems.

Typical problems include:

- missing values
- duplicate records
- inconsistent categories
- invalid dates
- numbers stored as text
- currency symbols embedded in numeric fields
- inconsistent capitalization
- leading and trailing spaces
- invalid email addresses
- malformed phone numbers
- impossible business values
- outliers that require investigation
- inconsistent identifiers

## 2. What is data manipulation?

Data manipulation is the controlled transformation of data into a structure that supports analysis, reporting, modeling, or operational use.

Examples include:

- selecting columns
- filtering rows
- creating variables
- joining tables
- grouping and aggregating
- reshaping data

## 3. Cleaning versus manipulation

Cleaning focuses on data quality. Manipulation focuses on changing the structure or representation of data for a purpose. In real projects, the two activities overlap.

## 4. Raw, clean, tidy, transformed, and analysis-ready data

**Raw data** is the source as received.

**Clean data** has known quality issues addressed according to documented rules.

**Tidy data** follows the principle that each variable is a column, each observation is a row, and each observational unit forms a table.

**Transformed data** has been deliberately changed for analysis.

**Analysis-ready data** has passed the relevant quality and validation checks for its intended use.

## 5. Reproducibility

Never rely on manually editing the Excel file and then forgetting what changed. A reproducible R script or notebook should make the transformation repeatable.

# PART 2 - R and RStudio Environment

Recommended setup:

1. Install R.
2. Install RStudio.
3. Create an R Project for the course.
4. Keep raw files separate from cleaned outputs.
5. Prefer relative file paths inside the project.
6. Record package versions for important production workflows.

A useful project structure is:

```text
data-cleaning-course/
├── data/
│   ├── raw/
│   ├── interim/
│   └── processed/
├── R/
├── notebooks/
├── outputs/
└── README.md
```

### Packages used in this masterclass

The core stack is the tidyverse, supported by `readxl`, `janitor`, `lubridate`, `data.table`, `arrow`, `jsonlite`, `DBI`, and `odbc` where appropriate.

In [1]:
# Install once if required
install.packages(c(
  "tidyverse",
  "readxl",
  "janitor",
  "lubridate",
  "data.table",
  "arrow",
  "jsonlite",
  "DBI",
  "odbc",
  "skimr"
))

# Load packages for the session
library(tidyverse)
library(readxl)
library(janitor)
library(lubridate)
library(data.table)

# Namespace usage avoids ambiguous function names
dplyr::filter
stats::filter

Installing packages into 'C:/Users/user/AppData/Local/R/win-library/4.5'
(as 'lib' is unspecified)

also installing the dependency 'assertthat'


Warning message in download.file(urls, destfiles, "libcurl", mode = "wb", ...):
"URL 'https://cran.r-project.org/bin/windows/contrib/4.5/arrow_25.0.1.zip': status was 'Failure when receiving data from the peer'"
Warning message in download.file(urls, destfiles, "libcurl", mode = "wb", ...):
"URL 'https://cran.r-project.org/bin/windows/contrib/4.5/jsonlite_2.0.0.zip': status was 'Failed sending data to the peer'"
Warning message in download.file(urls, destfiles, "libcurl", mode = "wb", ...):
"URL 'https://cran.r-project.org/bin/windows/contrib/4.5/DBI_1.3.0.zip': status was 'Failed sending data to the peer'"
Warning message in download.file(urls, destfiles, "libcurl", mode = "wb", ...):
"URL 'https://cran.r-project.org/bin/windows/contrib/4.5/odbc_1.7.1.zip': status was 'Failed sending data to the peer'"
Warning message in download.file(urls, destfiles, "libcurl", mode = "wb", ...):
"URL 'https://cran.r-project.org/bin/windows/contrib/4.5/skimr_2.2.2.zip': status was 'Failed sending data to the peer'"
Warning message in download.file(urls, destfiles, "libcurl", mode = "wb", ...):
"some files were not downloaded"
Warning message in download.packages(pkgs, destdir = tmpd, available = available, :
"download of package 'arrow' failed"
Warning message in download.packages(pkgs, destdir = tmpd, available = available, :
"download of package 'jsonlite' failed"
Warning message in download.packages(pkgs, destdir = tmpd, available = available, :
"download of package 'DBI' failed"
Warning message in download.packages(pkgs, destdir = tmpd, available = available, :
"download of package 'odbc' failed"
Warning message in download.packages(pkgs, destdir = tmpd, available = available, :
"download of package 'skimr' failed"

package 'assertthat' successfully unpacked and MD5 sums checked
package 'tidyverse' successfully unpacked and MD5 sums checked
package 'readxl' successfully unpacked and MD5 sums checked

Warning message:
"cannot remove prior installation of package 'readxl'"
Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problem copying C:\Users\user\AppData\Local\R\win-library\4.5\00LOCK\readxl\libs\x64\readxl.dll to C:\Users\user\AppData\Local\R\win-library\4.5\readxl\libs\x64\readxl.dll: Permission denied"
Warning message:
"restored 'readxl'"

package 'janitor' successfully unpacked and MD5 sums checked
package 'lubridate' successfully unpacked and MD5 sums checked

Warning message:
"cannot remove prior installation of package 'lubridate'"
Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problem copying C:\Users\user\AppData\Local\R\win-library\4.5\00LOCK\lubridate\libs\x64\lubridate.dll to C:\Users\user\AppData\Local\R\win-library\4.5\lubridate\libs\x64\lubridate.dll: Permission denied"
Warning message:
"restored 'lubridate'"

package 'data.table' successfully unpacked and MD5 sums checked

Warning message:
"cannot remove prior installation of package 'data.table'"
Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problem copying C:\Users\user\AppData\Local\R\win-library\4.5\00LOCK\data.table\libs\x64\data_table.dll to C:\Users\user\AppData\Local\R\win-library\4.5\data.table\libs\x64\data_table.dll: Permission denied"
Warning message:
"restored 'data.table'"

The downloaded binary packages are in
	C:\Users\user\AppData\Local\Temp\RtmpInMcVV\downloaded_packages

Warning message:
"package 'tidyverse' was built under R version 4.5.3"
Warning message:
"package 'ggplot2' was built under R version 4.5.3"
Warning message:
"package 'tibble' was built under R version 4.5.3"
Warning message:
"package 'tidyr' was built under R version 4.5.3"
Warning message:
"package 'readr' was built under R version 4.5.3"
Warning message:
"package 'purrr' was built under R version 4.5.3"
Warning message:
"package 'dplyr' was built under R version 4.5.3"
Warning message:
"package 'forcats' was built under R version 4.5.3"
Warning message:
"package 'lubridate' was built under R version 4.5.3"
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Warning message:
"package 'readxl' was built under R version 4.5.3"
Warning message:
"package 'janitor' was built under R version 4.5.3"

Attaching package: 'janitor'


The following objects are masked from 'package:stats':

    chisq.test, fisher.test


Warning message:
"package 'data.table' was built under R version 4.5.3"

Attaching package: 'data.table'


The following objects are masked from 'package:lubridate':

    hour, isoweek, isoyear, mday, minute, month, quarter, second, wday,
    week, yday, year


The following objects are masked from 'package:dplyr':

    between, first, last


The following object is masked from 'package:purrr':

    transpose

function (.data, ..., .by = NULL, .preserve = FALSE)
{
    check_by_typo(...)
    check_not_both_by_and_preserve({
        {
            .by
        }
    }, .preserve)
    UseMethod("filter")
}
<bytecode: 0x00000247153bd8e8>
<environment: namespace:dplyr>

function (x, filter, method = c("convolution", "recursive"),
    sides = 2L, circular = FALSE, init = NULL)
{
    method <- match.arg(method)
    x <- as.ts(x)
    storage.mode(x) <- "double"
    xtsp <- tsp(x)
    n <- as.integer(NROW(x))
    if (is.na(n))
        stop(gettextf("invalid value of %s", "NROW(x)"), domain = NA)
    nser <- NCOL(x)
    filter <- as.double(filter)
    nfilt <- as.integer(length(filter))
    if (is.na(nfilt))
        stop(gettextf("invalid value of %s", "length(filter)"),
            domain = NA)
    if (anyNA(filter))
        stop("missing values in 'filter'")
    if (method == "convolution") {
        if (nfilt > n)
            stop("'filter' is longer than time series")
        sides <- as.integer(sides)
        if (is.na(sides) || (sides != 1L && sides != 2L))
            stop("argument 'sides' must be 1 or 2")
        circular <- as.logical(circular)
        if (is.na(circular))
            stop("'circular' must be logical and not NA")
        if (is.matrix(x)) {
            y <- matrix(NA, n, nser)
            for (i in seq_len(nser)) y[, i] <- .Call(C_cfilter,
                x[, i], filter, sides, circular)
        }
        else y <- .Call(C_cfilter, x, filter, sides, circular)
    }
    else {
        if (missing(init)) {
            init <- matrix(0, nfilt, nser)
        }
        else {
            ni <- NROW(init)
            if (ni != nfilt)
                stop("length of 'init' must equal length of 'filter'")
            if (NCOL(init) != 1L && NCOL(init) != nser) {
                stop(sprintf(ngettext(nser, "'init' must have %d column",
                  "'init' must have 1 or %d columns", domain = "R-stats"),
                  nser), domain = NA)
            }
            if (!is.matrix(init))
                dim(init) <- c(nfilt, nser)
        }
        ind <- seq_len(nfilt)
        if (is.matrix(x)) {
            y <- matrix(NA, n, nser)
            for (i in seq_len(nser)) y[, i] <- .Call(C_rfilter,
                x[, i], filter, c(rev(init[, i]), double(n)))[-ind]
        }
        else y <- .Call(C_rfilter, x, filter, c(rev(init[, 1L]),
            double(n)))[-ind]
    }
    tsp(y) <- xtsp
    class(y) <- if (nser > 1L)
        c("mts", "ts")
    else "ts"
    y
}
<bytecode: 0x000002471fc686b8>
<environment: namespace:stats>

# PART 3 - R Data Structures for Cleaning

Important structures:

- atomic vectors
- character vectors
- numeric vectors
- integer vectors
- logical vectors
- factors
- lists
- matrices
- arrays
- data frames
- tibbles

Important inspection tools include:

`[]`, `[[]]`, `$`, `which()`, `length()`, `names()`, `dim()`, `nrow()`, `ncol()`, `str()`, `class()`, and `typeof()`.

A data-cleaning analyst should be comfortable moving between a whole table, a column, and individual values.

In [2]:
# Core inspection examples
x <- c("Lagos", "Abuja", "Ibadan", NA_character_)

x[1]
x[[1]]
x
length(x)
names(x) <- c("a", "b", "c", "d")
names(x)
which(is.na(x))

demo_df <- tibble(
  id = 1:4,
  city = x,
  active = c(TRUE, FALSE, TRUE, NA)
)

str(demo_df)
class(demo_df)
typeof(demo_df)
dim(demo_df)
nrow(demo_df)
ncol(demo_df)

[1] "Lagos"

[1] "Lagos"

[1] "Lagos"  "Abuja"  "Ibadan" NA

[1] 4

[1] "a" "b" "c" "d"

d
4

tibble [4 × 3] (S3: tbl_df/tbl/data.frame)
 $ id    : int [1:4] 1 2 3 4
 $ city  : Named chr [1:4] "Lagos" "Abuja" "Ibadan" NA
  ..- attr(*, "names")= chr [1:4] "a" "b" "c" "d"
 $ active: logi [1:4] TRUE FALSE TRUE NA

[1] "tbl_df"     "tbl"        "data.frame"

[1] "list"

[1] 4 3

[1] 4

[1] 3

# PART 4 - Importing the Uploaded Excel Dataset

We now connect the course to the supplied workbook.

The code below uses the uploaded workbook path. In an RStudio project, copy the workbook into the project's `data/raw/` folder and use a relative path for a portable workflow.

In [3]:
# Read the workbook
file_path <- "robust_dirty_powerbi_dataset.xlsx"

# See all sheets
excel_sheets(file_path)

# Read the first sheet
raw_data <- read_excel(file_path)

# Initial inspection immediately after import
head(raw_data)
tail(raw_data)
glimpse(raw_data)
dim(raw_data)
names(raw_data)

[1] "Sales_Data" "Customers"  "Products"

  OrderID Date         Customer Name  Region Sales Amount Product Quantity
1 1001    NA           John Doe       PH     N/A          Laptop  3
2 1002    March 3 2024 Rachel Zane    Abuja  50000        Monitor 1
3 1003    2024/01/05   Harvey Specter NA     45000        Tablet  1
4 1004    NA           Rachel Zane    NA     50000        Phone   NA
5 1005    NA           Louis Litt     PH     60000        Monitor 1
6 1006    March 3 2024 Rachel Zane    NA     45000        Phone   4

  OrderID Date         Customer Name  Region Sales Amount Product Quantity
1 1095    March 3 2024 Donna Paulsen  Abuja  N/A          Monitor 4
2 1096    05-02-2024   Louis Litt     NA     70000NGN     Phone   NA
3 1097    March 3 2024 Harvey Specter NA     70000NGN     Phone   NA
4 1098    2024/01/05   Harvey Specter PH     N/A          Tablet  NA
5 1099    NA           Jane Doe       Kano   50000        Laptop  4
6 1100    NA           Rachel Zane    NA     NA           Monitor 1

Rows: 100
Columns: 7
$ OrderID         <dbl> 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, …
$ Date            <chr> NA, "March 3 2024", "2024/01/05", NA, NA, "March 3 202…
$ `Customer Name` <chr> "John Doe", "Rachel Zane", "Harvey Specter", "Rachel Z…
$ Region          <chr> "PH", "Abuja", NA, NA, "PH", NA, "lagos", NA, "Abuja",…
$ `Sales Amount`  <chr> "N/A", "50000", "45000", "50000", "60000", "45000", "7…
$ Product         <chr> "Laptop", "Monitor", "Tablet", "Phone", "Monitor", "Ph…
$ Quantity        <chr> "3", "1", "1", NA, "1", "4", "1", "4", "3", "4", "3", …

[1] 100   7

[1] "OrderID"       "Date"          "Customer Name" "Region"
[5] "Sales Amount"  "Product"       "Quantity"

## Importing other common formats

### CSV

```r
read.csv("file.csv")
readr::read_csv("file.csv")
```

### TSV

```r
readr::read_tsv("file.tsv")
```

### JSON

```r
jsonlite::fromJSON("file.json")
```

### SQL

```r
DBI::dbConnect(...)
DBI::dbGetQuery(...)
```

### Parquet

```r
arrow::read_parquet("file.parquet")
```

When importing, always think about:

- encoding
- delimiters
- headers
- column types
- missing-value markers
- date parsing
- quoting
- escape characters
- locale
- decimal separators
- thousands separators

# PART 5 - Initial Data Inspection and Data Profiling

A professional cleaning workflow begins with an audit before transformations are applied.

The questions are:

- How large is the dataset?
- What are the columns?
- What are the data types?
- How many missing values exist?
- Are identifiers unique?
- Are categories consistent?
- Are numeric ranges plausible?
- Are there duplicates?
- Are there suspicious values?

Do not start changing values before understanding the source.

In [4]:
# Basic profiling
head(raw_data)
tail(raw_data)
glimpse(raw_data)
str(raw_data)
summary(raw_data)
dim(raw_data)
nrow(raw_data)
ncol(raw_data)
names(raw_data)

# Distinct values for selected columns
# Replace column names below after inspecting your workbook
# unique(raw_data$customer_id)
# n_distinct(raw_data$customer_id)

  OrderID Date         Customer Name  Region Sales Amount Product Quantity
1 1001    NA           John Doe       PH     N/A          Laptop  3
2 1002    March 3 2024 Rachel Zane    Abuja  50000        Monitor 1
3 1003    2024/01/05   Harvey Specter NA     45000        Tablet  1
4 1004    NA           Rachel Zane    NA     50000        Phone   NA
5 1005    NA           Louis Litt     PH     60000        Monitor 1
6 1006    March 3 2024 Rachel Zane    NA     45000        Phone   4

  OrderID Date         Customer Name  Region Sales Amount Product Quantity
1 1095    March 3 2024 Donna Paulsen  Abuja  N/A          Monitor 4
2 1096    05-02-2024   Louis Litt     NA     70000NGN     Phone   NA
3 1097    March 3 2024 Harvey Specter NA     70000NGN     Phone   NA
4 1098    2024/01/05   Harvey Specter PH     N/A          Tablet  NA
5 1099    NA           Jane Doe       Kano   50000        Laptop  4
6 1100    NA           Rachel Zane    NA     NA           Monitor 1

Rows: 100
Columns: 7
$ OrderID         <dbl> 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, …
$ Date            <chr> NA, "March 3 2024", "2024/01/05", NA, NA, "March 3 202…
$ `Customer Name` <chr> "John Doe", "Rachel Zane", "Harvey Specter", "Rachel Z…
$ Region          <chr> "PH", "Abuja", NA, NA, "PH", NA, "lagos", NA, "Abuja",…
$ `Sales Amount`  <chr> "N/A", "50000", "45000", "50000", "60000", "45000", "7…
$ Product         <chr> "Laptop", "Monitor", "Tablet", "Phone", "Monitor", "Ph…
$ Quantity        <chr> "3", "1", "1", NA, "1", "4", "1", "4", "3", "4", "3", …
tibble [100 × 7] (S3: tbl_df/tbl/data.frame)
 $ OrderID      : num [1:100] 1001 1002 1003 1004 1005 ...
 $ Date         : chr [1:100] NA "March 3 2024" "2024/01/05" NA ...
 $ Customer Name: chr [1:100] "John Doe" "Rachel Zane" "Harvey Specter" "Rachel Zane" ...
 $ Region       : chr [1:100] "PH" "Abuja" NA NA ...
 $ Sales Amount : chr [1:100] "N/A" "50000" "45000" "50000" ...
 $ Product      : chr [1:100] "Laptop" "Monitor" "Tablet" "Phone" ...
 $ Quantity     : chr [1:100] "3" "1" "1" NA ...

    OrderID         Date           Customer Name         Region
 Min.   :1001   Length:100         Length:100         Length:100
 1st Qu.:1026   Class :character   Class :character   Class :character
 Median :1050   Mode  :character   Mode  :character   Mode  :character
 Mean   :1050
 3rd Qu.:1075
 Max.   :1100
 Sales Amount         Product            Quantity
 Length:100         Length:100         Length:100
 Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character

[1] 100   7

[1] 100

[1] 7

[1] "OrderID"       "Date"          "Customer Name" "Region"
[5] "Sales Amount"  "Product"       "Quantity"

In [5]:
# Generic column-level profiling
profile <- tibble(
  column = names(raw_data),
  data_type = map_chr(raw_data, ~ class(.x)[1]),
  missing_count = map_int(raw_data, ~ sum(is.na(.x))),
  missing_percent = map_dbl(raw_data, ~ mean(is.na(.x)) * 100),
  unique_values = map_int(raw_data, ~ n_distinct(.x, na.rm = TRUE))
) %>%
  arrange(desc(missing_percent))

profile

              column        data_type missing_count missing_percent
Date          Date          character 45            45
Region        Region        character 21            21
Sales Amount  Sales Amount  character 17            17
Quantity      Quantity      character 16            16
Customer Name Customer Name character 12            12
OrderID       OrderID       numeric    0             0
Product       Product       character  0             0
              unique_values
Date            3
Region          5
Sales Amount    5
Quantity        4
Customer Name   7
OrderID       100
Product         4

## Data-quality checklist

For each column, document:

| Check | Question |
|---|---|
| Completeness | How much data is missing? |
| Validity | Are values allowed? |
| Consistency | Are equivalent values represented consistently? |
| Uniqueness | Are duplicate records or IDs present? |
| Accuracy | Do values plausibly represent reality? |
| Timeliness | Is the data current enough? |
| Integrity | Do relationships between tables remain valid? |

This checklist becomes the foundation for a data-quality report.

# PART 6 - Column Name Cleaning

Messy names make every downstream operation harder.

Common problems:

- spaces
- punctuation
- inconsistent capitalization
- duplicated names
- abbreviations
- excessively long names
- non-syntactic names

`janitor::clean_names()` is especially useful for standardizing a dataset to `snake_case`.

In [6]:
# Inspect original names
names(raw_data)

# Create a cleaned copy
cleaned <- raw_data %>%
  janitor::clean_names()

names(cleaned)

# Manual renaming
# cleaned <- cleaned %>%
#   rename(
#     customer_id = old_customer_identifier,
#     order_date = old_order_date
#   )

# Dynamic renaming
# cleaned <- cleaned %>%
#   rename_with(~ str_to_lower(.x))

[1] "OrderID"       "Date"          "Customer Name" "Region"
[5] "Sales Amount"  "Product"       "Quantity"

[1] "order_id"      "date"          "customer_name" "region"
[5] "sales_amount"  "product"       "quantity"

# PART 7 - Data Types and Type Conversion

A column that looks numeric may actually be character data.

Common examples:

- `"₦1,250,000"` stored as text
- `"15%"` stored as text
- `"2026-01-31"` stored as character
- `"Yes"` and `"Y"` mixed in a logical field

Always inspect before converting.

In [7]:
# Inspect types
glimpse(cleaned)
sapply(cleaned, class)

# Base R conversions
# as.character(x)
# as.numeric(x)
# as.integer(x)
# as.logical(x)
# as.factor(x)
# as.Date(x)

# Safer parsing with readr
# parse_number("₦1,250,000")
# parse_double("1250.50")
# parse_integer("1250")
# parse_logical("TRUE")
# parse_date("2026-01-31")
# parse_datetime("2026-01-31 14:30:00")

Rows: 100
Columns: 7
$ order_id      <dbl> 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 10…
$ date          <chr> NA, "March 3 2024", "2024/01/05", NA, NA, "March 3 2024"…
$ customer_name <chr> "John Doe", "Rachel Zane", "Harvey Specter", "Rachel Zan…
$ region        <chr> "PH", "Abuja", NA, NA, "PH", NA, "lagos", NA, "Abuja", N…
$ sales_amount  <chr> "N/A", "50000", "45000", "50000", "60000", "45000", "700…
$ product       <chr> "Laptop", "Monitor", "Tablet", "Phone", "Monitor", "Phon…
$ quantity      <chr> "3", "1", "1", NA, "1", "4", "1", "4", "3", "4", "3", NA…

     order_id          date customer_name        region  sales_amount
    "numeric"   "character"   "character"   "character"   "character"
      product      quantity
  "character"   "character"

## Type-conversion warning

Never use `as.numeric()` blindly on messy currency or percentage text.

For example:

```r
as.numeric("₦1,250,000")
```

does not perform currency-aware parsing.

A safer approach is often:

```r
readr::parse_number("₦1,250,000")
```

Similarly, percentages need a deliberate rule. Decide whether `"15%"` should become `15` or `0.15` before converting.

# PART 8 - Missing Data

Missingness is not one single thing.

Distinguish:

- `NA`
- `NULL`
- `NaN`
- `Inf`
- empty strings
- blank cells
- `"N/A"`
- `"NA"`
- `"Unknown"`
- `"Not Available"`
- `"Missing"`
- `"?"`
- sentinel values such as `-999`

Do not automatically replace every missing value. The correct treatment depends on what missingness means in the business process.

In [8]:
# Core missing-value checks
is.na(cleaned)
anyNA(cleaned)
complete.cases(cleaned)

# Count missing values by column
missing_summary <- tibble(
  column = names(cleaned),
  missing_count = map_int(cleaned, ~ sum(is.na(.x))),
  missing_percent = map_dbl(cleaned, ~ mean(is.na(.x)) * 100)
) %>%
  arrange(desc(missing_percent))

missing_summary

# Rows containing at least one missing value
missing_rows <- cleaned %>%
  filter(if_any(everything(), is.na))

missing_rows

      order_id date  customer_name region sales_amount product quantity
 [1,] FALSE     TRUE FALSE         FALSE  FALSE        FALSE   FALSE
 [2,] FALSE    FALSE FALSE         FALSE  FALSE        FALSE   FALSE
 [3,] FALSE    FALSE FALSE          TRUE  FALSE        FALSE   FALSE
 [4,] FALSE     TRUE FALSE          TRUE  FALSE        FALSE    TRUE
 [5,] FALSE     TRUE FALSE         FALSE  FALSE        FALSE   FALSE
 [6,] FALSE    FALSE FALSE          TRUE  FALSE        FALSE   FALSE
 [7,] FALSE     TRUE FALSE         FALSE  FALSE        FALSE   FALSE
 [8,] FALSE     TRUE FALSE          TRUE  FALSE        FALSE   FALSE
 [9,] FALSE     TRUE FALSE         FALSE   TRUE        FALSE   FALSE
[10,] FALSE    FALSE  TRUE          TRUE  FALSE        FALSE   FALSE
[11,] FALSE    FALSE FALSE         FALSE  FALSE        FALSE   FALSE
[12,] FALSE    FALSE  TRUE         FALSE  FALSE        FALSE    TRUE
[13,] FALSE    FALSE  TRUE         FALSE  FALSE        FALSE   FALSE
[14,] FALSE    FALSE FALSE         FALSE  FALSE        FALSE   FALSE
[15,] FALSE     TRUE FALSE          TRUE  FALSE        FALSE   FALSE
[16,] FALSE     TRUE FALSE         FALSE   TRUE        FALSE   FALSE
[17,] FALSE    FALSE  TRUE         FALSE  FALSE        FALSE    TRUE
[18,] FALSE     TRUE  TRUE          TRUE  FALSE        FALSE    TRUE
[19,] FALSE    FALSE FALSE          TRUE  FALSE        FALSE   FALSE
[20,] FALSE    FALSE  TRUE          TRUE  FALSE        FALSE   FALSE
[21,] FALSE     TRUE FALSE         FALSE  FALSE        FALSE   FALSE
[22,] FALSE     TRUE FALSE         FALSE  FALSE        FALSE    TRUE
[23,] FALSE    FALSE FALSE         FALSE  FALSE        FALSE   FALSE
[24,] FALSE     TRUE FALSE         FALSE  FALSE        FALSE   FALSE
[25,] FALSE    FALSE  TRUE         FALSE  FALSE        FALSE   FALSE
[26,] FALSE    FALSE FALSE         FALSE  FALSE        FALSE    TRUE
[27,] FALSE     TRUE FALSE         FALSE   TRUE        FALSE   FALSE
[28,] FALSE    FALSE  TRUE         FALSE  FALSE        FALSE   FALSE
[29,] FALSE    FALSE  TRUE         FALSE  FALSE        FALSE   FALSE
[30,] FALSE     TRUE FALSE          TRUE  FALSE        FALSE    TRUE
[31,] ⋮        ⋮     ⋮             ⋮      ⋮            ⋮       ⋮
[32,] FALSE    FALSE FALSE         FALSE  FALSE        FALSE   FALSE
[33,] FALSE    FALSE FALSE         FALSE  FALSE        FALSE    TRUE
[34,] FALSE    FALSE FALSE         FALSE  FALSE        FALSE   FALSE
[35,] FALSE    FALSE  TRUE         FALSE  FALSE        FALSE   FALSE
[36,] FALSE    FALSE FALSE         FALSE  FALSE        FALSE   FALSE
[37,] FALSE     TRUE FALSE          TRUE  FALSE        FALSE   FALSE
[38,] FALSE     TRUE FALSE          TRUE  FALSE        FALSE   FALSE
[39,] FALSE     TRUE FALSE         FALSE  FALSE        FALSE    TRUE
[40,] FALSE    FALSE FALSE         FALSE  FALSE        FALSE   FALSE
[41,] FALSE    FALSE FALSE         FALSE  FALSE        FALSE   FALSE
[42,] FALSE    FALSE FALSE         FALSE  FALSE        FALSE   FALSE
[43,] FALSE    FALSE FALSE         FALSE  FALSE        FALSE   FALSE
[44,] FALSE    FALSE FALSE         FALSE  FALSE        FALSE   FALSE
[45,] FALSE    FALSE FALSE         FALSE  FALSE        FALSE    TRUE
[46,] FALSE     TRUE FALSE         FALSE   TRUE        FALSE   FALSE
[47,] FALSE     TRUE  TRUE         FALSE  FALSE        FALSE   FALSE
[48,] FALSE     TRUE FALSE         FALSE   TRUE        FALSE   FALSE
[49,] FALSE    FALSE FALSE         FALSE  FALSE        FALSE   FALSE
[50,] FALSE    FALSE FALSE         FALSE   TRUE        FALSE   FALSE
[51,] FALSE    FALSE FALSE         FALSE  FALSE        FALSE   FALSE
[52,] FALSE     TRUE FALSE         FALSE  FALSE        FALSE   FALSE
[53,] FALSE     TRUE FALSE         FALSE   TRUE        FALSE   FALSE
[54,] FALSE     TRUE FALSE         FALSE  FALSE        FALSE   FALSE
[55,] FALSE    FALSE FALSE          TRUE  FALSE        FALSE   FALSE
[56,] FALSE    FALSE FALSE         FALSE  FALSE        FALSE   FALSE
[57,] FALSE    FALSE FALSE          TRUE  FALSE        FALSE    TRUE
[58,] FALSE    FALSE FALSE          TRUE  FALSE        FALSE    TRUE
[59,] FALSE    FALSE FALSE         FALSE  FALSE        FALSE    TRUE
[60,] FALSE     TRUE FALSE         FALSE  FALSE        FALSE   FALSE
[61,] FALSE     TRUE FALSE          TRUE   TRUE        FALSE   FALSE

[1] TRUE

  [1] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE
 [13] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE
 [25] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE FALSE FALSE  TRUE  TRUE
 [37] FALSE  TRUE FALSE  TRUE  TRUE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE
 [49] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE
 [61] FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE
 [73]  TRUE FALSE  TRUE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [85] FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE
 [97] FALSE FALSE FALSE FALSE

              column        missing_count missing_percent
date          date          45            45
region        region        21            21
sales_amount  sales_amount  17            17
quantity      quantity      16            16
customer_name customer_name 12            12
order_id      order_id       0             0
product       product        0             0

   order_id date         customer_name  region sales_amount product quantity
1  1001     NA           John Doe       PH     N/A          Laptop  3
2  1003     2024/01/05   Harvey Specter NA     45000        Tablet  1
3  1004     NA           Rachel Zane    NA     50000        Phone   NA
4  1005     NA           Louis Litt     PH     60000        Monitor 1
5  1006     March 3 2024 Rachel Zane    NA     45000        Phone   4
6  1007     NA           Mike Ross      lagos  70000NGN     Phone   1
7  1008     NA           John Doe       NA     N/A          Monitor 4
8  1009     NA           Donna Paulsen  Abuja  NA           Phone   3
9  1010     March 3 2024 NA             NA     50000        Laptop  4
10 1012     05-02-2024   NA             Lagos  50000        Tablet  NA
11 1013     2024/01/05   NA             Kano   45000        Phone   3
12 1015     NA           Harvey Specter NA     50000        Phone   2
13 1016     NA           Harvey Specter Abuja  NA           Phone   3
14 1017     March 3 2024 NA             lagos  70000NGN     Tablet  NA
15 1018     NA           NA             NA     50000        Phone   NA
16 1019     2024/01/05   Jane Doe       NA     N/A          Monitor 4
17 1020     2024/01/05   NA             NA     50000        Monitor 3
18 1021     NA           Mike Ross      lagos  60000        Laptop  2
19 1022     NA           Louis Litt     PH     60000        Phone   NA
20 1024     NA           Donna Paulsen  Kano   N/A          Tablet  3
21 1025     05-02-2024   NA             PH     60000        Phone   4
22 1026     March 3 2024 Mike Ross      Abuja  N/A          Phone   NA
23 1027     NA           John Doe       Lagos  NA           Laptop  2
24 1028     2024/01/05   NA             Abuja  50000        Phone   3
25 1029     March 3 2024 NA             Kano   45000        Tablet  2
26 1030     NA           Louis Litt     NA     70000NGN     Phone   NA
27 1033     05-02-2024   Jane Doe       NA     70000NGN     Monitor 2
28 1034     NA           Jane Doe       Lagos  NA           Laptop  2
29 1037     NA           Mike Ross      Abuja  NA           Monitor 4
30 1039     NA           Rachel Zane    Lagos  50000        Tablet  NA
⋮  ⋮        ⋮            ⋮              ⋮      ⋮            ⋮       ⋮
44 1057     NA           Donna Paulsen  PH     50000        Laptop  1
45 1058     NA           NA             PH     NA           Monitor 3
46 1060     05-02-2024   Harvey Specter lagos  45000        Laptop  NA
47 1061     NA           Jane Doe       lagos  50000        Tablet  4
48 1062     05-02-2024   Mike Ross      Kano   NA           Phone   1
49 1063     NA           John Doe       lagos  70000NGN     Tablet  3
50 1065     NA           Louis Litt     Lagos  NA           Phone   4
51 1066     NA           Rachel Zane    PH     45000        Monitor 1
52 1067     NA           Rachel Zane    PH     70000NGN     Monitor 4
53 1068     NA           Mike Ross      Abuja  70000NGN     Tablet  1
54 1070     05-02-2024   John Doe       NA     50000        Laptop  1
55 1072     2024/01/05   John Doe       Abuja  45000        Phone   NA
56 1074     05-02-2024   NA             Abuja  N/A          Monitor 3
57 1076     NA           Harvey Specter NA     70000NGN     Laptop  3
58 1077     NA           Rachel Zane    NA     70000NGN     Phone   2
59 1078     NA           Donna Paulsen  lagos  N/A          Tablet  NA
60 1084     2024/01/05   Rachel Zane    lagos  70000NGN     Laptop  NA
61 1085     NA           Jane Doe       Lagos  NA           Laptop  1
62 1086     NA           NA             Abuja  60000        Phone   4
63 1087     NA           John Doe       Lagos  NA           Phone   3
64 1089     05-02-2024   Jane Doe       Abuja  NA           Tablet  3
65 1091     NA           Donna Paulsen  Kano   N/A          Phone   3
66 1092     NA           Jane Doe       Abuja  NA           Tablet  2
67 1093     NA           Mike Ross      PH     50000        Phone   3
68 1094     2024/01/05   Jane Doe       NA     70000NGN     Tablet  1
69 1096     05-02-2024   Louis Litt     NA     70000NGN     Phone   NA
70 1097     March 3 2024 Harvey Specter NA     70000NGN     Phone   NA
71 1098     2024/01/05   Harvey Specter PH     N/A          Tablet  NA
72 1099     NA           Jane Doe       Kano   50000        Laptop  4
73 1100     NA           Rachel Zane    NA     NA           Monitor 1

In [9]:
# Standardize common textual missing markers
missing_markers <- c("", "NA", "N/A", "Unknown", "Not Available", "Missing", "?")

cleaned_missing <- cleaned %>%
  mutate(
    across(
      where(is.character),
      ~ na_if(str_squish(.x), "")
    )
  )

# For additional markers:
cleaned_missing <- cleaned_missing %>%
  mutate(
    across(
      where(is.character),
      ~ if_else(.x %in% missing_markers, NA_character_, .x)
    )
  )

## Missing-data strategies

Possible approaches include:

- leave missing values as `NA`
- remove rows only when justified
- mean imputation
- median imputation
- mode imputation
- constant replacement
- group-based imputation
- time-based filling
- interpolation
- model-based imputation

Missing-data mechanisms are commonly described as:

**MCAR** - Missing Completely At Random  
**MAR** - Missing At Random conditional on observed information  
**MNAR** - Missing Not At Random

The mechanism matters because replacing values can introduce bias.

In [10]:
# Tidyverse missing-value operations
# tidyr::replace_na()
# tidyr::drop_na()
# tidyr::fill()

# Example: median imputation for one numeric variable
# cleaned <- cleaned %>%
#   mutate(
#     income = replace_na(income, median(income, na.rm = TRUE))
#   )

# Example: group-based median
# cleaned <- cleaned %>%
#   group_by(region) %>%
#   mutate(
#     income = replace_na(income, median(income, na.rm = TRUE))
#   ) %>%
#   ungroup()

# PART 9 - Duplicate Data

Duplicates may be:

- exact duplicate rows
- duplicate customer IDs
- duplicate transactions
- duplicate business events
- near-duplicates caused by spelling or formatting differences

The correct duplicate rule depends on the grain of the table.

In [11]:
# Exact duplicates
sum(duplicated(cleaned))

duplicated_rows <- cleaned[duplicated(cleaned), ]
duplicated_rows

# Tidyverse equivalent
cleaned %>% distinct()

# Duplicate business keys
# cleaned %>%
#   count(customer_id) %>%
#   filter(n > 1)

# Keep the first row for a duplicated identifier
# cleaned %>%
#   distinct(customer_id, .keep_all = TRUE)

[1] 0

     order_id date customer_name region sales_amount product quantity

    order_id date         customer_name  region sales_amount product quantity
1   1001     NA           John Doe       PH     N/A          Laptop  3
2   1002     March 3 2024 Rachel Zane    Abuja  50000        Monitor 1
3   1003     2024/01/05   Harvey Specter NA     45000        Tablet  1
4   1004     NA           Rachel Zane    NA     50000        Phone   NA
5   1005     NA           Louis Litt     PH     60000        Monitor 1
6   1006     March 3 2024 Rachel Zane    NA     45000        Phone   4
7   1007     NA           Mike Ross      lagos  70000NGN     Phone   1
8   1008     NA           John Doe       NA     N/A          Monitor 4
9   1009     NA           Donna Paulsen  Abuja  NA           Phone   3
10  1010     March 3 2024 NA             NA     50000        Laptop  4
11  1011     March 3 2024 Mike Ross      Lagos  60000        Tablet  3
12  1012     05-02-2024   NA             Lagos  50000        Tablet  NA
13  1013     2024/01/05   NA             Kano   45000        Phone   3
14  1014     2024/01/05   Harvey Specter Abuja  45000        Phone   4
15  1015     NA           Harvey Specter NA     50000        Phone   2
16  1016     NA           Harvey Specter Abuja  NA           Phone   3
17  1017     March 3 2024 NA             lagos  70000NGN     Tablet  NA
18  1018     NA           NA             NA     50000        Phone   NA
19  1019     2024/01/05   Jane Doe       NA     N/A          Monitor 4
20  1020     2024/01/05   NA             NA     50000        Monitor 3
21  1021     NA           Mike Ross      lagos  60000        Laptop  2
22  1022     NA           Louis Litt     PH     60000        Phone   NA
23  1023     05-02-2024   Harvey Specter PH     45000        Phone   1
24  1024     NA           Donna Paulsen  Kano   N/A          Tablet  3
25  1025     05-02-2024   NA             PH     60000        Phone   4
26  1026     March 3 2024 Mike Ross      Abuja  N/A          Phone   NA
27  1027     NA           John Doe       Lagos  NA           Laptop  2
28  1028     2024/01/05   NA             Abuja  50000        Phone   3
29  1029     March 3 2024 NA             Kano   45000        Tablet  2
30  1030     NA           Louis Litt     NA     70000NGN     Phone   NA
⋮   ⋮        ⋮            ⋮              ⋮      ⋮            ⋮       ⋮
71  1071     March 3 2024 Mike Ross      Kano   45000        Laptop  1
72  1072     2024/01/05   John Doe       Abuja  45000        Phone   NA
73  1073     March 3 2024 Rachel Zane    lagos  60000        Tablet  2
74  1074     05-02-2024   NA             Abuja  N/A          Monitor 3
75  1075     2024/01/05   John Doe       Abuja  70000NGN     Phone   3
76  1076     NA           Harvey Specter NA     70000NGN     Laptop  3
77  1077     NA           Rachel Zane    NA     70000NGN     Phone   2
78  1078     NA           Donna Paulsen  lagos  N/A          Tablet  NA
79  1079     March 3 2024 John Doe       Lagos  70000NGN     Tablet  3
80  1080     March 3 2024 Jane Doe       Abuja  50000        Tablet  2
81  1081     2024/01/05   Donna Paulsen  Lagos  60000        Laptop  4
82  1082     March 3 2024 Donna Paulsen  Lagos  N/A          Laptop  3
83  1083     March 3 2024 Louis Litt     PH     70000NGN     Laptop  4
84  1084     2024/01/05   Rachel Zane    lagos  70000NGN     Laptop  NA
85  1085     NA           Jane Doe       Lagos  NA           Laptop  1
86  1086     NA           NA             Abuja  60000        Phone   4
87  1087     NA           John Doe       Lagos  NA           Phone   3
88  1088     March 3 2024 Donna Paulsen  lagos  70000NGN     Monitor 1
89  1089     05-02-2024   Jane Doe       Abuja  NA           Tablet  3
90  1090     2024/01/05   Donna Paulsen  Abuja  45000        Phone   3
91  1091     NA           Donna Paulsen  Kano   N/A          Phone   3
92  1092     NA           Jane Doe       Abuja  NA           Tablet  2
93  1093     NA           Mike Ross      PH     50000        Phone   3
94  1094     2024/01/05   Jane Doe       NA     70000NGN     Tablet  1
95  1095     March 3 2024 Donna Paulsen  Abuja  N/A          Monitor 4
96  1096     05-02-2024   Louis Litt     NA     70000NGN     Phone   NA
97  1097     March 3 2024 Harvey Specter NA     70000NGN     Phone   NA
98  1098     2024/01/05   Harvey Specter PH     N/A          Tablet  NA
99  1099     NA           Jane Doe       Kano   50000        Laptop  4
100 1100     NA           Rachel Zane    NA     NA           Monitor 1

## Duplicate-retention decision

Do not delete duplicates merely because `duplicated()` returns `TRUE`.

Ask:

1. What is one row supposed to represent?
2. Is the repeated ID legitimate?
3. Is this a transaction table or a customer table?
4. Which record is authoritative?
5. Is one record newer?
6. Which record has more complete information?
7. Can the records be safely consolidated?

This is a business-rule decision, not only a coding decision.

# PART 10 - Selecting and Removing Columns

Use `select()` to control the analysis surface.

Important helpers:

- `starts_with()`
- `ends_with()`
- `contains()`
- `matches()`
- `num_range()`
- `all_of()`
- `any_of()`
- `everything()`
- `where()`

In [12]:
# Examples
# select(cleaned, customer_id, age, income)
# select(cleaned, -unnecessary_column)
# select(cleaned, starts_with("sales"))
# select(cleaned, ends_with("_id"))
# select(cleaned, contains("date"))
# select(cleaned, where(is.numeric))
# select(cleaned, everything())

# PART 11 - Renaming Columns

Use `rename()` for explicit mappings and `rename_with()` for systematic transformations.

In [13]:
# Explicit
# cleaned <- cleaned %>%
#   rename(
#     customer_id = customer_identifier,
#     total_sales = sales_amount
#   )

# Systematic
cleaned <- cleaned %>%
  rename_with(~ str_to_lower(.x))

# janitor can standardize names further
cleaned <- cleaned %>%
  janitor::clean_names()

# PART 12 - Filtering Rows

`filter()` keeps rows that satisfy logical conditions.

Important operators:

- `==`
- `!=`
- `>`
- `<`
- `>=`
- `<=`
- `%in%`
- `&`
- `|`
- `!`

Special helpers include `between()` and `near()`.

In [14]:
# Generic examples
# filter(cleaned, age > 30)
# filter(cleaned, gender == "Female")
# filter(cleaned, region %in% c("North", "South"))
# filter(cleaned, age >= 20 & age <= 40)
# filter(cleaned, amount > 100000 | status == "High")
# filter(cleaned, !is.na(customer_id))
# filter(cleaned, between(age, 20, 40))

# Important:
# filter() does not treat NA as TRUE.
# If a condition evaluates to NA, that row is normally removed.

# PART 13 - Sorting

`arrange()` controls row order. `desc()` reverses the ordering of a variable.

In [15]:
# arrange(cleaned, age)
# arrange(cleaned, desc(income))
# arrange(cleaned, region, desc(income))
# arrange(cleaned, is.na(income), income)

# PART 14 - Creating and Transforming Variables

`mutate()` creates or modifies columns.

Common uses:

- ratios
- percentages
- flags
- categories
- date features
- string features
- business metrics

In [16]:
# Generic examples
# cleaned <- cleaned %>%
#   mutate(
#     profit = revenue - cost,
#     margin = profit / revenue,
#     high_value = revenue >= 1000000
#   )

# transmute() keeps only variables created or selected
# cleaned %>%
#   transmute(customer_id, revenue, profit = revenue - cost)

# PART 15 - Conditional Transformations

Use `if_else()`, `case_when()`, `case_match()`, `recode()`, and `coalesce()` deliberately.

`case_when()` is especially useful for business classification.

In [17]:
# Age groups
# cleaned <- cleaned %>%
#   mutate(
#     age_group = case_when(
#       age < 18 ~ "Under 18",
#       age < 30 ~ "18-29",
#       age < 45 ~ "30-44",
#       age < 60 ~ "45-59",
#       age >= 60 ~ "60+",
#       TRUE ~ "Unknown"
#     )
#   )

# coalesce() returns the first non-missing value
# mutate(cleaned, final_email = coalesce(primary_email, secondary_email))

# PART 16 - String Cleaning with stringr

Text is one of the most common sources of dirty data.

Typical problems:

- `" Lagos"` versus `"Lagos "`
- `"LAGOS"` versus `"lagos"`
- multiple spaces
- punctuation
- inconsistent phone formatting
- malformed emails
- inconsistent names
- product-code variations

Useful functions:

`str_detect()`, `str_extract()`, `str_extract_all()`, `str_replace()`, `str_replace_all()`, `str_remove()`, `str_remove_all()`, `str_split()`, `str_sub()`, `str_trim()`, `str_squish()`, `str_to_lower()`, `str_to_upper()`, `str_to_title()`, `str_length()`, `str_c()`, and `str_glue()`.

In [18]:
# Common text-cleaning pipeline
# cleaned <- cleaned %>%
#   mutate(
#     name = name %>% str_squish() %>% str_to_title(),
#     email = email %>% str_squish() %>% str_to_lower(),
#     city = city %>% str_squish() %>% str_to_title()
#   )

# Detect text patterns
# str_detect(email, fixed("@"))
# str_length(name)
# str_sub(product_code, 1, 3)

# Replace characters
# str_replace_all(phone, "[^0-9]", "")

# PART 17 - Regular Expressions

Regex provides a powerful way to identify patterns.

Core concepts:

- literal characters
- character classes
- quantifiers
- anchors
- groups
- alternation
- escaping
- capturing groups

Examples of pattern logic:

```text
^        start of string
$        end of string
[0-9]    digit
[A-Za-z] letter
\\s      whitespace
+        one or more
*        zero or more
?        optional
|        OR
()       group
```

In [19]:
# Email pattern - teaching example, not a complete RFC implementation
email_pattern <- "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$"

# str_detect(cleaned$email, email_pattern)

# Phone normalization example
# cleaned <- cleaned %>%
#   mutate(phone_digits = str_replace_all(phone, "[^0-9]", ""))

# Product-code extraction example
# str_extract(product_code, "[A-Z]{2}[0-9]{4}")

# PART 18 - Factors and Categorical Data

Factors are important when categorical variables have a defined set or order of levels.

`forcats` provides tools for:

- renaming levels
- reordering levels
- collapsing levels
- lumping rare categories
- dropping unused levels

In [20]:
# Examples
# library(forcats)

# cleaned <- cleaned %>%
#   mutate(
#     status = factor(status),
#     status = fct_relevel(status, "Active", "Inactive")
#   )

# fct_recode(status, Active = "active", Inactive = "inactive")
# fct_collapse(status, Other = c("Unknown", "Not Available"))
# fct_lump(status, n = 5)
# fct_drop(status)

# PART 19 - Numeric Data Cleaning

Numeric problems include:

- currency symbols
- thousands separators
- decimal separators
- negative values
- impossible zeros
- infinite values
- extreme values
- excessive precision

Useful functions include:

`round()`, `ceiling()`, `floor()`, `abs()`, `sign()`, `log()`, and `sqrt()`.

In [21]:
# Numeric diagnostics
# summary(cleaned$amount)
# quantile(cleaned$amount, na.rm = TRUE)
# sum(is.infinite(cleaned$amount), na.rm = TRUE)

# Convert Inf and -Inf to NA when appropriate
# cleaned <- cleaned %>%
#   mutate(across(where(is.numeric), ~ if_else(is.infinite(.x), NA_real_, .x)))

# Rounding
# cleaned <- cleaned %>%
#   mutate(amount = round(amount, 2))

# PART 20 - Outlier Detection

An outlier is not automatically an error.

Investigate whether it is:

- a genuine unusual observation
- a data-entry error
- a unit mismatch
- a duplicate
- a legitimate business event

Approaches:

1. domain rules
2. IQR
3. z-score
4. standard deviation
5. percentiles
6. visual inspection
7. robust statistics

In [22]:
# IQR method for a numeric vector
x <- cleaned %>% 
  select(where(is.numeric)) %>% 
  pull(1)

q1 <- quantile(x, 0.25, na.rm = TRUE)
q3 <- quantile(x, 0.75, na.rm = TRUE)
iqr_value <- IQR(x, na.rm = TRUE)

lower <- q1 - 1.5 * iqr_value
upper <- q3 + 1.5 * iqr_value

outlier_flag <- x < lower | x > upper
table(outlier_flag, useNA = "ifany")

# Visual investigation
# boxplot(x)

outlier_flag
FALSE
  100

# PART 21 - Date and Time Cleaning with lubridate

Date cleaning is critical in finance, sales, operations, customer analytics, and event data.

Core functions:

- `ymd()`
- `mdy()`
- `dmy()`
- `ymd_hms()`
- `year()`
- `month()`
- `day()`
- `hour()`
- `minute()`
- `second()`
- `wday()`
- `floor_date()`
- `ceiling_date()`
- `round_date()`

In [23]:
# Examples
ymd("2026-09-28")
dmy("28-09-2026")
mdy("09/28/2026")

# Date components
example_date <- ymd("2026-09-28")
year(example_date)
month(example_date)
day(example_date)
wday(example_date)

# Time
ymd_hms("2026-09-28 11:30:00")

# Period grouping
floor_date(example_date, "month")
ceiling_date(example_date, "quarter")

[1] "2026-09-28"

[1] "2026-09-28"

[1] "2026-09-28"

[1] 2026

[1] 9

[1] 28

[1] 2

[1] "2026-09-28 11:30:00 UTC"

[1] "2026-09-01"

[1] "2026-10-01"

## Date-quality checks

Examples of business rules:

- order date cannot be before customer registration date
- future transaction dates may require investigation
- invalid calendar dates must be rejected
- timezone assumptions should be documented
- date strings should use one consistent interpretation

Do not silently guess between day-month-year and month-day-year when ambiguity matters.

# PART 22 - Reshaping Data with tidyr

A clean analytical dataset often needs to be reshaped.

### Wide

One observation may have multiple measurement columns.

### Long

Repeated measurements become rows, usually with one column identifying the variable and another containing its value.

Core functions:

- `pivot_longer()`
- `pivot_wider()`
- `separate()`
- `separate_wider_delim()`
- `unite()`
- `separate_rows()`

In [24]:
# Generic wide-to-long example
sales_wide <- tibble(
  customer = c("A", "B"),
  jan = c(100, 120),
  feb = c(110, 130),
  mar = c(125, 140)
)

sales_long <- sales_wide %>%
  pivot_longer(
    cols = jan:mar,
    names_to = "month",
    values_to = "sales"
)

sales_long

# Long-to-wide
sales_long %>%
  pivot_wider(
    names_from = month,
    values_from = sales
)

  customer month sales
1 A        jan   100
2 A        feb   110
3 A        mar   125
4 B        jan   120
5 B        feb   130
6 B        mar   140

  customer jan feb mar
1 A        100 110 125
2 B        120 130 140

# PART 23 - Nested and Complex Data

R can work with list-columns and nested data.

Important functions:

- `nest()`
- `unnest()`
- `unnest_longer()`
- `unnest_wider()`

These become useful when working with JSON-like structures, grouped models, APIs, and nested records.

In [25]:
# Simple nested-data example
nested <- tibble(
  region = c("North", "South"),
  data = list(
    tibble(customer = c("A", "B"), sales = c(100, 200)),
    tibble(customer = c("C", "D"), sales = c(150, 250))
  )
)

nested

nested %>%
  unnest(data)

  region data <NA> <NA> <NA>
1 North  A    100  C    150
2 South  B    200  D    250

  region customer sales
1 North  A        100
2 North  B        200
3 South  C        150
4 South  D        250

# PART 24 - Grouping and Aggregation

Core functions:

- `group_by()`
- `ungroup()`
- `summarise()`
- `reframe()`
- `count()`
- `tally()`

### `mutate()` versus `summarise()`

With grouping:

- `mutate()` generally preserves the row-level grain and adds group-aware calculations.
- `summarise()` collapses each group into summary rows.

Understanding table grain is essential before aggregating.

In [26]:
# Generic examples
# cleaned %>%
#   group_by(region) %>%
#   summarise(
#     customers = n(),
#     average_income = mean(income, na.rm = TRUE),
#     median_income = median(income, na.rm = TRUE)
#   )

# Grouped missingness
# cleaned %>%
#   group_by(region) %>%
#   summarise(
#     missing_income = sum(is.na(income)),
#     total = n()
#   )

# PART 25 - Window Functions

Window functions calculate values while preserving row-level detail.

Useful functions include:

- `row_number()`
- `min_rank()`
- `dense_rank()`
- `percent_rank()`
- `cume_dist()`
- `lag()`
- `lead()`
- cumulative functions such as `cumsum()` and `cummean()`

In [27]:
# Generic ranking
# cleaned %>%
#   group_by(region) %>%
#   mutate(
#     sales_rank = min_rank(desc(sales)),
#     previous_sales = lag(sales),
#     running_sales = cumsum(sales)
#   ) %>%
#   ungroup()

# PART 26 - Joins and Data Integrity

Before joining, identify:

- primary keys
- foreign keys
- table grain
- expected relationship

Relationships can be:

- one-to-one
- one-to-many
- many-to-many

Join functions:

- `left_join()`
- `right_join()`
- `inner_join()`
- `full_join()`
- `semi_join()`
- `anti_join()`

A major professional risk is unexpected row multiplication caused by duplicate join keys.

In [28]:
# Example tables
customers <- tibble(
  customer_id = c(1, 2, 3),
  customer_name = c("Ada", "Bola", "Chidi")
)

transactions <- tibble(
  transaction_id = c(101, 102, 103, 104),
  customer_id = c(1, 1, 2, 4),
  amount = c(100, 150, 200, 50)
)

left_join(customers, transactions, by = "customer_id")
right_join(customers, transactions, by = "customer_id")
inner_join(customers, transactions, by = "customer_id")
full_join(customers, transactions, by = "customer_id")

# Find transactions without a matching customer
anti_join(transactions, customers, by = "customer_id")

  customer_id customer_name transaction_id amount
1 1           Ada           101            100
2 1           Ada           102            150
3 2           Bola          103            200
4 3           Chidi          NA             NA

  customer_id customer_name transaction_id amount
1 1           Ada           101            100
2 1           Ada           102            150
3 2           Bola          103            200
4 4           NA            104             50

  customer_id customer_name transaction_id amount
1 1           Ada           101            100
2 1           Ada           102            150
3 2           Bola          103            200

  customer_id customer_name transaction_id amount
1 1           Ada           101            100
2 1           Ada           102            150
3 2           Bola          103            200
4 3           Chidi          NA             NA
5 4           NA            104             50

  transaction_id customer_id amount
1 104            4           50

## Join diagnostics

Before joining:

```r
transactions %>%
  count(customer_id) %>%
  filter(n > 1)
```

Ask whether repeated keys are expected.

After joining, compare:

```r
nrow(left_table)
nrow(joined_table)
```

If row counts change unexpectedly, investigate the relationship instead of assuming the join is correct.

# PART 27 - Concatenating Datasets

Use:

- `bind_rows()` to stack observations
- `bind_cols()` to place columns side-by-side

Before binding, verify schema consistency.

In [29]:
# Example
a <- tibble(id = 1:2, sales = c(100, 200))
b <- tibble(id = 3:4, sales = c(150, 250))

bind_rows(a, b)

# bind_cols() requires compatible row alignment
bind_cols(a, tibble(region = c("North", "South")))

  id sales
1 1  100
2 2  200
3 3  150
4 4  250

  id sales region
1 1  100   North
2 2  200   South

# PART 28 - Data Validation

Cleaning is incomplete until the resulting dataset is validated.

Validation categories:

1. range checks
2. type checks
3. uniqueness
4. referential integrity
5. required fields
6. allowed categories
7. logical consistency
8. business rules
9. cross-field validation

In [30]:
# Example validation rules
validation <- cleaned %>%
  summarise(
    negative_age = sum(age < 0, na.rm = TRUE),
    missing_id = sum(is.na(customer_id)),
    negative_quantity = sum(quantity < 0, na.rm = TRUE),
    invalid_percentage = sum(percentage < 0 | percentage > 100, na.rm = TRUE)
  )

validation

ERROR: Error in `summarise()`:
ℹ In argument: `negative_age = sum(age < 0, na.rm = TRUE)`.
Caused by error:
! object 'age' not found

# PART 29 - Data Quality Framework

Seven practical dimensions:

- **Accuracy** - Does the value represent reality?
- **Completeness** - Are required values present?
- **Consistency** - Are equivalent values represented consistently?
- **Validity** - Does the value conform to allowed rules?
- **Uniqueness** - Are duplicates controlled?
- **Timeliness** - Is the data current enough?
- **Integrity** - Do relationships between records remain valid?

A professional project should document the quality checks and their results.

# PART 30 - EDA as a Data-Cleaning Tool

EDA can expose quality problems that are difficult to see from raw tables.

Useful visual checks:

- histograms
- boxplots
- bar charts
- scatterplots
- frequency tables
- group summaries
- correlations

Examples of issues revealed by EDA:

- unexpected outliers
- skewed distributions
- incorrect categories
- impossible values
- suspicious relationships
- unusual missingness patterns

In [ ]:
# Basic ggplot checks
# ggplot(cleaned, aes(x = numeric_variable)) +
#   geom_histogram()

# ggplot(cleaned, aes(y = numeric_variable)) +
#   geom_boxplot()

# ggplot(cleaned, aes(x = category)) +
#   geom_bar()

# ggplot(cleaned, aes(x = x_variable, y = y_variable)) +
#   geom_point()

# PART 31 - Advanced dplyr

Important modern tools include:

- `across()`
- `if_any()`
- `if_all()`
- `pick()`
- `where()`
- `cur_group()`
- `cur_column()`

Use these to apply consistent transformations or checks across many columns.

In [ ]:
# Clean whitespace across every character column
cleaned <- cleaned %>%
  mutate(
    across(
      where(is.character),
      ~ str_squish(.x)
    )
  )

# Standardize character case where appropriate
# cleaned <- cleaned %>%
#   mutate(across(where(is.character), str_to_lower))

# Find rows where any selected value is missing
# cleaned %>%
#   filter(if_any(everything(), is.na))

# PART 32 - Applying Functions Across Columns

A major advantage of `across()` is eliminating repetitive code.

Examples:

- trim every character field
- replace sentinel values
- round numeric measures
- calculate missingness
- identify invalid values

In [ ]:
# Missingness across all columns
missing_by_row <- cleaned %>%
  mutate(missing_fields = rowSums(across(everything(), is.na)))

missing_by_row %>%
  arrange(desc(missing_fields)) %>%
  head(20)

# PART 33 - purrr and Functional Data Manipulation

`purrr` is useful when the same operation must be applied to many objects.

Core functions:

`map()`, `map_chr()`, `map_dbl()`, `map_int()`, `map_lgl()`, `map_dfr()`, `map2()`, `pmap()`, `walk()`, `possibly()`, `safely()`.

In [ ]:
# Apply a function to every column
column_classes <- map_chr(cleaned, ~ class(.x)[1])
column_classes

# Missing counts
missing_counts <- map_int(cleaned, ~ sum(is.na(.x)))
missing_counts

# Convert results into a table
tibble(
  column = names(missing_counts),
  missing_count = missing_counts
)

# PART 34 - Cleaning Multiple Files

A common real-world pattern is monthly or departmental files.

Workflow:

1. locate files
2. read each file
3. standardize schema
4. apply the same cleaning function
5. combine
6. validate the combined dataset

In [ ]:
# Example pattern
files <- list.files(
  path = "data/raw",
  pattern = "\\.csv$",
  full.names = TRUE
)

# Example when every file shares a compatible schema:
# all_months <- files %>%
#   map(readr::read_csv) %>%
#   map(clean_customer_data) %>%
#   list_rbind()

files

# PART 35 - Automating Data Cleaning

Reusable functions turn a notebook experiment into a repeatable data pipeline.

In [ ]:
clean_customer_data <- function(df) {
  required_columns <- c("customer_id")

  missing_required <- setdiff(required_columns, names(df))

  if (length(missing_required) > 0) {
    stop(
      "Missing required columns: ",
      paste(missing_required, collapse = ", ")
    )
  }

  df %>%
    janitor::clean_names() %>%
    mutate(
      across(where(is.character), ~ str_squish(.x))
    )
}

# Example:
# cleaned_final <- clean_customer_data(raw_data)

# PART 36 - Error Handling

Production data pipelines must anticipate failures.

Examples:

- malformed dates
- unexpected numeric values
- missing columns
- incorrect file formats
- unavailable APIs
- unexpected schemas

Tools:

- `try()`
- `tryCatch()`
- `purrr::possibly()`
- `purrr::safely()`

In [ ]:
safe_read_csv <- purrr::possibly(
  readr::read_csv,
  otherwise = NULL
)

# Example:
# result <- safe_read_csv("missing_file.csv")
# result

# PART 37 - data.table

For large datasets, `data.table` provides a high-performance alternative.

The central expression is:

```r
DT[i, j, by]
```

Conceptually:

- `i` filters rows
- `j` selects/transforms/aggregates
- `by` defines groups

It also supports updating by reference, which can reduce unnecessary copying.

In [ ]:
# Convert a data frame to data.table
DT <- as.data.table(cleaned)

# Examples
# DT[age > 30]
# DT[, .(avg_income = mean(income, na.rm = TRUE)), by = region]
# DT[, new_flag := amount > 100000]

# PART 38 - Large Datasets and Performance

When datasets become large, cleaning strategy must consider memory and execution time.

Important ideas:

- select only required columns
- filter early when appropriate
- prefer vectorized operations
- avoid unnecessary copies
- use `data.table` for suitable workloads
- use Arrow and Parquet for columnar storage
- consider database-side processing for very large relational data

### Parquet

Parquet is a columnar file format that can be efficient for analytical workloads.

```r
arrow::write_parquet(cleaned, "cleaned_data.parquet")
cleaned_again <- arrow::read_parquet("cleaned_data.parquet")
```

# PART 39 - Base R versus tidyverse

Both approaches are valuable.

| Task | Base R | Tidyverse |
|---|---|---|
| Filter rows | `df[df$x > 10, ]` | `filter(df, x > 10)` |
| Select columns | `df[c("x", "y")]` | `select(df, x, y)` |
| Create column | `df$new <- ...` | `mutate(df, new = ...)` |
| Summarize | `aggregate()` | `summarise()` |
| Combine rows | `rbind()` | `bind_rows()` |
| Rename | `names()` | `rename()` |

Use the approach that produces clear, reliable, maintainable code. The tidyverse is particularly expressive for data-wrangling pipelines, while base R remains fundamental and widely used.

# PART 40 - Complete Practical Cleaning Pipeline

The following template brings the major concepts together.

The exact business rules should be adapted after inspecting the actual column names in the workbook.

In [ ]:
# ============================================================
# COMPLETE DATA CLEANING PIPELINE TEMPLATE
# Kajola Gbenga
# Data Scientist & AI Engineer
# ============================================================

library(tidyverse)
library(readxl)
library(janitor)
library(lubridate)

# 1. Import
raw <- read_excel("robust_dirty_powerbi_dataset.xlsx")

# 2. Preserve the raw data
clean <- raw

# 3. Standardize column names
clean <- clean %>%
  clean_names()

# 4. Standardize character fields
clean <- clean %>%
  mutate(
    across(
      where(is.character),
      ~ str_squish(.x)
    )
  )

# 5. Convert known textual missing markers
missing_markers <- c("", "N/A", "NA", "Unknown", "Not Available", "?")

clean <- clean %>%
  mutate(
    across(
      where(is.character),
      ~ if_else(.x %in% missing_markers, NA_character_, .x)
    )
  )

# 6. Inspect the result
glimpse(clean)

# 7. Profile missingness
quality_report <- tibble(
  column = names(clean),
  missing_count = map_int(clean, ~ sum(is.na(.x))),
  missing_percent = map_dbl(clean, ~ mean(is.na(.x)) * 100),
  unique_count = map_int(clean, ~ n_distinct(.x, na.rm = TRUE))
)

quality_report

# 8. Duplicate audit
duplicate_count <- sum(duplicated(clean))
duplicate_count

# 9. Validate required business rules
# Add project-specific rules here.

# 10. Export only after validation
# write_csv(clean, "cleaned_data.csv")
# write_parquet(clean, "cleaned_data.parquet")

# PART 41 - Practical Exercises Using the Uploaded Dataset

These exercises should be completed against the supplied workbook.

## Beginner exercises

1. Import the workbook.
2. Display the first 10 rows.
3. Display the number of rows and columns.
4. List all column names.
5. Display the structure of the dataset.
6. Calculate missing values per column.
7. Identify duplicate rows.
8. Clean the column names with `janitor`.
9. Find character columns.
10. Find numeric columns.

## Intermediate exercises

11. Standardize whitespace in all character columns.
12. Identify inconsistent category labels.
13. Convert appropriate columns to numeric.
14. Parse date columns.
15. Create a missingness percentage report.
16. Identify columns with more than 20% missing values.
17. Investigate duplicated business identifiers.
18. Create a business-rule validation table.
19. Detect potential numeric outliers.
20. Create at least three derived variables.

## Advanced exercises

21. Build a reusable cleaning function.
22. Create a validation function.
23. Build a data-quality scorecard.
24. Create a clean-versus-raw comparison.
25. Produce an audit log of transformations.
26. Build a pipeline that can process multiple monthly files.
27. Add error handling for missing columns.
28. Validate join keys before merging.
29. Export the final dataset to CSV and Parquet.
30. Document every business rule used to transform the data.

# PART 42 - Capstone Project

## Business scenario

You have been given a messy operational dataset and asked to deliver an analysis-ready dataset for a business intelligence and analytics team.

### Deliverables

**Deliverable 1 - Raw data audit**

Document:

- row count
- column count
- data types
- missingness
- duplicate records
- suspicious values
- inconsistent categories

**Deliverable 2 - Cleaning script**

Build a reproducible R script that:

- imports the raw workbook
- standardizes names
- standardizes text
- converts data types
- handles missing markers
- addresses duplicates according to documented rules
- validates business constraints

**Deliverable 3 - Data-quality report**

Include:

- completeness
- validity
- consistency
- uniqueness
- integrity
- suspicious-value counts

**Deliverable 4 - Analysis-ready dataset**

Export:

```text
cleaned_data.csv
cleaned_data.parquet
```

**Deliverable 5 - Documentation**

Explain:

- what was changed
- why it was changed
- what was not changed
- which assumptions were made
- which records require human review

### Professional standard

A strong cleaning pipeline should make it possible for another analyst to reproduce the result without manually editing the source workbook.

# PART 43 - Data Cleaning Audit Log

A professional workflow should record transformations.

A useful audit-log structure is:

| Step | Column | Issue | Action | Rule | Records affected |
|---|---|---|---|---|---|
| 1 | email | extra spaces | trim | `str_squish()` | count |
| 2 | amount | currency text | parse | `parse_number()` | count |
| 3 | status | inconsistent labels | standardize | mapping table | count |
| 4 | date | text date | parse | documented format | count |

Example R structure:

In [ ]:
audit_log <- tibble(
  step = integer(),
  column = character(),
  issue = character(),
  action = character(),
  rule = character(),
  records_affected = integer()
)

audit_log

# PART 44 - Final Validation Checklist

Before delivering a cleaned dataset, ask:

### Structure

- Are column names standardized?
- Is the table at the correct grain?
- Are unnecessary columns removed?

### Types

- Are numbers truly numeric?
- Are dates true dates?
- Are categories represented appropriately?
- Are logical fields consistent?

### Missingness

- Are missing markers standardized?
- Are missing values treated according to business meaning?
- Are imputation decisions documented?

### Duplicates

- Are exact duplicates understood?
- Are business-key duplicates investigated?
- Were legitimate repeated transactions preserved?

### Text

- Are spaces standardized?
- Is capitalization consistent?
- Are emails and IDs validated?
- Are categories standardized?

### Numeric values

- Are currencies parsed correctly?
- Are percentages interpreted correctly?
- Are impossible values identified?
- Are outliers investigated rather than blindly deleted?

### Dates

- Are date formats consistent?
- Are invalid dates handled?
- Are timezone assumptions documented?

### Relationships

- Are join keys valid?
- Did joins create unexpected row multiplication?
- Are unmatched records understood?

### Validation

- Do business rules pass?
- Are record counts reasonable?
- Can the cleaning process be reproduced?

### Delivery

- Is the final dataset exported?
- Is the cleaning code saved?
- Is the audit log documented?
- Are unresolved data-quality issues reported?

# PART 45 - Instructor Notes

### Teaching sequence

A practical classroom sequence is:

**Session 1:** Foundations, R environment, data structures, importing, inspection

**Session 2:** Column names, types, missing values, duplicates

**Session 3:** Selecting, filtering, sorting, mutation, conditional transformations

**Session 4:** String cleaning, regex, categorical data

**Session 5:** Numeric cleaning, outliers, dates and times

**Session 6:** Reshaping, grouping, aggregation, window functions

**Session 7:** Joins, validation, data quality, EDA for cleaning

**Session 8:** Advanced `dplyr`, `purrr`, reusable functions, error handling

**Session 9:** Multiple-file automation, `data.table`, Arrow, Parquet

**Session 10:** Capstone project using the uploaded dirty dataset

### Instructor emphasis

Learners should repeatedly answer three questions:

1. **What is wrong with the data?**
2. **Why is the chosen cleaning rule appropriate?**
3. **How do we prove the cleaned result is correct?**

That mindset is more important than memorizing individual functions.

# Final Summary

Data cleaning with R is a complete analytical discipline, not a collection of isolated commands.

The professional workflow is:

```text
Raw Data
   ↓
Import
   ↓
Profile
   ↓
Identify Quality Problems
   ↓
Define Cleaning Rules
   ↓
Transform
   ↓
Validate
   ↓
Document
   ↓
Export
   ↓
Analysis / BI / Machine Learning
```

The supplied workbook should be treated as the raw source. The final cleaned dataset should always remain distinguishable from the original so that transformations remain traceable and reproducible.

---

**Kajola Gbenga**  
**Data Scientist & AI Engineer**